import type { Experience, Partner, Region } from "@/lib/content/types";

// Demo content loaded into Payload by `npm run seed`. Partner names and prices are
// placeholders, not real operators or quotes. Edit real content in /admin instead.

export const regions: Region[] = [
  {
    slug: "nairobi",
    name: "Nairobi",
    tagline: "A national park on the city's edge",
    description:
      "Game drives within sight of the skyline, the Giraffe Centre, Karen, and food and nightlife tours.",
    center: { lat: -1.2921, lng: 36.8219 },
    liteZoom: 10,
  },
  {
    slug: "maasai-mara",
    name: "Maasai Mara",
    tagline: "Big cats, balloons and the great migration",
    description:
      "Game drives, balloon safaris at dawn and visits to Maasai villages on the conservancies.",
    center: { lat: -1.4061, lng: 35.0136 },
    liteZoom: 9,
  },
  {
    slug: "coast",
    name: "Coast",
    tagline: "Mombasa, Diani and Lamu",
    description: "Old Town walks, snorkelling on the reef and dhow trips at sunset.",
    center: { lat: -4.0435, lng: 39.6682 },
    liteZoom: 8,
  },
  {
    slug: "tsavo",
    name: "Tsavo / Voi",
    tagline: "Red elephants and lava country",
    description: "Tsavo East and West drives, Lugard Falls and Mudanda Rock.",
    center: { lat: -3.3961, lng: 38.5561 },
    liteZoom: 8,
  },
  {
    slug: "naivasha",
    name: "Naivasha",
    tagline: "Rift Valley lakes and gorges",
    description: "Boat rides, cycling through Hell's Gate and walks on Crescent Island.",
    center: { lat: -0.7167, lng: 36.4333 },
    liteZoom: 10,
  },
  {
    slug: "mt-kenya",
    name: "Nanyuki / Mt Kenya",
    tagline: "Peaks, rhinos and the equator",
    description: "Hikes on the mountain, Ol Pejeta visits and equator stops.",
    center: { lat: 0.0167, lng: 37.0667 },
    liteZoom: 9,
  },
];

const partner = (id: string, regionSlug: string, contractSigned = true): Partner => ({
  id,
  name: `Demo partner ${id.toUpperCase()}`,
  regionSlug,
  contractSigned,
});

export const partners: Partner[] = [
  ...["n1", "n2", "n3", "n4", "n5"].map((id) => partner(id, "nairobi")),
  ...["m1", "m2", "m3", "m4", "m5"].map((id) => partner(id, "maasai-mara")),
  partner("v1", "naivasha"),
  partner("v2", "naivasha"),
  partner("v3", "naivasha", false),
];

const parkFee = (amountKes: number) => ({
  kind: "park_kws" as const,
  label: "KWS park entry",
  basis: "per_person" as const,
  amountKes,
});

export const experiences: Experience[] = [
  {
    slug: "nairobi-national-park-drive",
    regionSlug: "nairobi",
    partnerId: "n1",
    type: "game_drive",
    title: "Nairobi National Park morning drive",
    summary: "Lions, rhinos and giraffes with the city skyline behind them.",
    description:
      "Leave at sunrise for a four-hour drive through the park in a pop-up roof vehicle with a local guide.",
    location: { lat: -1.3733, lng: 36.8581 },
    durationHours: 4,
    priceRules: [{ basis: "per_person", amountKes: 6500 }],
    fees: [
      parkFee(4300),
      { kind: "vehicle", label: "Pop-up roof vehicle", basis: "per_group", amountKes: 9000 },
    ],
    rating: { average: 4.8, count: 126 },
  },
  {
    slug: "giraffe-centre-and-karen",
    regionSlug: "nairobi",
    partnerId: "n2",
    type: "day_trip",
    title: "Giraffe Centre and Karen afternoon",
    summary: "Feed Rothschild giraffes, then tea in Karen.",
    description: "A relaxed half day: the Giraffe Centre, a craft market and afternoon tea.",
    location: { lat: -1.3765, lng: 36.7449 },
    durationHours: 5,
    priceRules: [{ basis: "per_person", amountKes: 5200 }],
    fees: [{ kind: "vehicle", label: "Transport", basis: "per_group", amountKes: 6000 }],
    rating: { average: 4.6, count: 88 },
  },
  {
    slug: "nairobi-street-food-tour",
    regionSlug: "nairobi",
    partnerId: "n3",
    type: "guided_walk",
    title: "Nairobi street food walk",
    summary: "Nyama choma, mutura and chapati with a local foodie.",
    description: "Three hours through the city's best food stalls, with tastings included.",
    location: { lat: -1.2833, lng: 36.8233 },
    durationHours: 3,
    priceRules: [{ basis: "per_person", amountKes: 4000 }],
    fees: [],
    rating: { average: 4.9, count: 54 },
  },
  {
    slug: "nairobi-nightlife-tour",
    regionSlug: "nairobi",
    partnerId: "n4",
    type: "activity",
    title: "Westlands live music night",
    summary: "Benga, gengetone and Afro-house in three venues.",
    description: "A hosted night out with transport between venues.",
    location: { lat: -1.2676, lng: 36.8108 },
    durationHours: 5,
    priceRules: [{ basis: "per_person", amountKes: 5500 }],
    fees: [{ kind: "vehicle", label: "Night transport", basis: "per_group", amountKes: 5000 }],
  },
  {
    slug: "karen-blixen-and-kazuri",
    regionSlug: "nairobi",
    partnerId: "n5",
    type: "cultural_visit",
    title: "Karen Blixen Museum and Kazuri beads",
    summary: "The Out of Africa house and a women-run bead workshop.",
    description: "A guided visit to the museum, then the Kazuri workshop and shop.",
    location: { lat: -1.3524, lng: 36.7126 },
    durationHours: 4,
    priceRules: [{ basis: "per_person", amountKes: 4800 }],
    fees: [{ kind: "vehicle", label: "Transport", basis: "per_group", amountKes: 5500 }],
  },
  {
    slug: "mara-full-day-game-drive",
    regionSlug: "maasai-mara",
    partnerId: "m1",
    type: "game_drive",
    title: "Full-day Mara game drive",
    summary: "Dawn to dusk on the plains, picnic lunch by the river.",
    description: "Ten hours in a 4x4 with a Maasai guide. Includes a picnic lunch.",
    location: { lat: -1.49, lng: 35.14 },
    durationHours: 10,
    priceRules: [
      { basis: "per_person", amountKes: 9500 },
      {
        basis: "per_person",
        amountKes: 12500,
        season: { from: "07-01", to: "10-31", label: "Migration season" },
      },
    ],
    fees: [
      {
        kind: "conservancy",
        label: "Reserve entry",
        basis: "per_person",
        amountKes: 13000,
      },
      { kind: "vehicle", label: "4x4 vehicle", basis: "per_group", amountKes: 15000 },
    ],
    rating: { average: 4.9, count: 312 },
  },
  {
    slug: "mara-balloon-safari",
    regionSlug: "maasai-mara",
    partnerId: "m2",
    type: "activity",
    title: "Sunrise balloon safari",
    summary: "An hour over the plains, then a bush breakfast.",
    description: "Pick-up before dawn, a one-hour flight and a champagne breakfast where you land.",
    location: { lat: -1.45, lng: 35.05 },
    durationHours: 4,
    priceRules: [{ basis: "per_person", amountKes: 58000 }],
    fees: [],
    rating: { average: 4.9, count: 201 },
  },
  {
    slug: "maasai-village-visit",
    regionSlug: "maasai-mara",
    partnerId: "m3",
    type: "cultural_visit",
    title: "Maasai village visit",
    summary: "Meet a manyatta community, hosted by its families.",
    description: "Two hours in the village: homes, beadwork, the adumu jumping dance and fire-making.",
    location: { lat: -1.38, lng: 35.1 },
    durationHours: 2,
    priceRules: [{ basis: "per_group", amountKes: 6000, maxGroup: 6 }],
    fees: [],
  },
  {
    slug: "mara-guided-bush-walk",
    regionSlug: "maasai-mara",
    partnerId: "m4",
    type: "guided_walk",
    title: "Conservancy bush walk",
    summary: "Track animals on foot with an armed ranger.",
    description: "A three-hour walk on a private conservancy, learning tracks and plants.",
    location: { lat: -1.3, lng: 35.2 },
    durationHours: 3,
    priceRules: [{ basis: "per_person", amountKes: 5000 }],
    fees: [{ kind: "guide", label: "Armed ranger", basis: "per_group", amountKes: 4000 }],
  },
  {
    slug: "mara-night-drive",
    regionSlug: "maasai-mara",
    partnerId: "m5",
    type: "game_drive",
    title: "Conservancy night drive",
    summary: "Hyenas, aardvarks and bush babies by spotlight.",
    description: "Two hours after dark on a conservancy, where night drives are allowed.",
    location: { lat: -1.33, lng: 35.25 },
    durationHours: 2,
    priceRules: [{ basis: "per_person", amountKes: 7000 }],
    fees: [{ kind: "conservancy", label: "Conservancy fee", basis: "per_person", amountKes: 6000 }],
  },
  {
    slug: "hells-gate-cycling",
    regionSlug: "naivasha",
    partnerId: "v1",
    type: "activity",
    title: "Hell's Gate cycling and gorge walk",
    summary: "Cycle past zebras, then walk the gorge.",
    description: "Bikes, a guide and park entry for a half day in Hell's Gate.",
    location: { lat: -0.9137, lng: 36.3122 },
    durationHours: 5,
    priceRules: [{ basis: "per_person", amountKes: 3500 }],
    fees: [parkFee(3000)],
  },
  {
    slug: "crescent-island-boat-walk",
    regionSlug: "naivasha",
    partnerId: "v2",
    type: "guided_walk",
    title: "Crescent Island boat and walk",
    summary: "Hippos from the boat, giraffes on foot.",
    description: "A boat across Lake Naivasha and a guided walk among the island's wildlife.",
    location: { lat: -0.7667, lng: 36.4 },
    durationHours: 3,
    priceRules: [{ basis: "per_group", amountKes: 9000, maxGroup: 8 }],
    fees: [{ kind: "conservancy", label: "Island entry", basis: "per_person", amountKes: 2500 }],
  },
];
